version: "3.9"
services:
  mlserver:
    image: mlserver_bench
    build: .
    volumes:
      - ./bench_server:/app/bench_server
      - ./server_config:/app/server_config
      - ./model_files:/app/model_files
    environment:
      PYTHONPATH: /app
    command: mlserver start /app/server_config
    ports:
      - "8080"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          cpus: '2'
          memory: 512M
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mlserver
    ports:
      - "9091:4000"


